post:
  max_title: 250
  min_title: 6
  min_content: 6
  extension:
    hot_question: "hot_question"
    recent_comment: "recent_comment"
comment:
  object_type:
    post: "post"
    answer: "answer"
topic:
  da_dang_location: 1
  ha_noi_location: 2
  hcmc_location: 3
  tk_location: 4
  handico_location: 5
  location: "location"
  q_a_number: 1
  feedback_number: 2
  confesstion_number: 3
  q_a: "1"
  feedback: "2"
  confesstion: "3"
  type_sort:
    recently: "newest"
    popular: "popular"
    recently_answer: "recently_answer"
    no_answer: "no_answer"
anonymous: "1"
max_search_tags: 5
plus_one: 1
paginate_offset: 1
paginate_default: 5
paginate_tags: 12
paginate_users: 8
paginate_posts: 10
id_user_hiddent: 1
hr_administrator: "Hr administrator"
recruiter: "Recruiter"
event_officer: "Event Officer"
content_max_length: 500
limit_top: 3
limit_tag: 10
limit_notification: 5
pictures:
  accepted_files: "image/jpeg, image/gif, image/png"
reaction_type:
  up: "upvote"
  down: "downvote"
  like: "like"
  dislike: "dislike"
  heart: "heart"
success: "success"
error: "error"
activities:
  items_per_page: 10
relationships:
  follow: "follow"
  unfollow: "unfollow"
limit_string:
  content: 200
  name: 50
  user_name: 25
  tag_name: 25
activity:
  key:
    follow: "create"
    unfollow: "destroy"
languages:
  vi: "vi"
  en: "en"
  ja: "ja"
index_zero_in_array: 0
index_one_in_array: 1
index_two_in_array: 2
index_three_in_array: 3
index_four_in_array: 4
index_five_in_array: 5
index_six_in_array: 6
index_seven_in_array: 7
index_eight_in_array: 8
index_nine_in_array: 9
serialize_true: "1"
serialize_false: "0"
from_mail: "fask.info@gmail.com"
scan_begin_index: 13
show_view_more: 3
paginate_comment: 3
not_view_more: 0
second_page: 2
one_page: 1
version_reject: 2
post_topic_qa: 1
version:
  accept: "accept"
  improve: "improve"
  reject: "reject"
  waiting: "waiting"
